[versions]
activityCompose = "1.12.1"
agp = "8.13.1"
appUpdate = "2.1.0"
barcodeScanning = "17.3.0"
camera = "1.5.2"
coilCompose = "2.7.0"
composeBom = "2025.12.00"
coreSplashscreen = "1.2.0"
datastore = "1.2.0"
firebaseBom = "34.6.0"
firebaseCrashlytics = "3.0.6"
googleServices = "4.4.4"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
firebasePerf = "2.0.2"
foundation = "1.10.0"
kotlinxCoroutinesTest = "1.10.2"
ktor = "3.3.3"
lifecycleViewmodelCompose = "2.10.0"
material = "1.13.0"
material3 = "1.5.0-alpha10"
materialIconsExtended = "1.7.8"
mockitoCore = "5.20.0"
mockitoKotlin = "6.1.0"
navigation = "2.9.6"
runtime = "1.10.0"
kotlin = "2.2.21"
turbine = "1.2.1"
uiGraphicsAndroid = "1.10.0"
zxingCore = "3.5.4"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

ui = { module = "androidx.compose.ui:ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtime" }
runtime-annotation = { group = "androidx.compose.runtime", name = "runtime-annotation", version.ref = "runtime" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "uiGraphicsAndroid" }
foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
foundation-android = { group = "androidx.compose.foundation", name = "foundation-android", version.ref = "foundation" }
foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundation" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }

lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }

navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }

datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }

ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "appUpdate" }
material = { module = "com.google.android.material:material", version.ref = "material" }

barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }

firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics-ndk = { module = "com.google.firebase:firebase-crashlytics-ndk" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }

google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }

zxing-core = { module = "com.google.zxing:core", version.ref = "zxingCore" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }

ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerf" }