[versions]
packageName = "com.andymic.esnscanner"

java = "11"
minAndroid = "26"
minIOS = "16.6"
targetAndroid = "36"

versionCode = "14"
versionName = "2.0.0"

ios-mlkit = "9.0.0"
ios-firebase = "12.7.0"

activityCompose = "1.12.2"
agp = "8.13.2"
appUpdate = "2.1.0"
barcodeScanning = "17.3.0"
camera = "1.5.2"
coilCompose = "3.3.0"
coilNetworkKtor = "3.0.0-alpha08"
composeMultiplatform = "1.9.3"
coreSplashscreen = "1.2.0"
datastore = "1.2.0"
firebaseBom = "34.7.0"
firebaseCrashlytics = "3.0.6"
firebasePerf = "2.0.2"
gitliveFirebase = "2.4.0"
googleServices = "4.4.4"
kotlinxCoroutinesPlayServices = "1.10.2"
kotlinxCoroutinesTest = "1.10.2"
kotlinxDatetime = "0.7.1"
ktor = "3.3.3"
lifecycle = "2.9.6"
material = "1.13.0"
navigation = "2.9.1"
qrKit = "3.1.3"
kotlin = "2.3.0"
turbine = "1.2.1"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }

navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor", version.ref = "coilNetworkKtor" }

gitlive-firebase-common = { module = "dev.gitlive:firebase-common", version.ref = "gitliveFirebase" }
gitlive-firebase-crashlytics = { module = "dev.gitlive:firebase-crashlytics", version.ref = "gitliveFirebase" }
gitlive-firebase-perf = { module = "dev.gitlive:firebase-perf", version.ref = "gitliveFirebase" }

coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }

datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "appUpdate" }
material = { module = "com.google.android.material:material", version.ref = "material" }

barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }

firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics-ndk = { module = "com.google.firebase:firebase-crashlytics-ndk" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }

google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }

qr-kit = { module = "network.chaintech:qr-kit", version.ref = "qrKit" }

ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-multiplatform = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }

compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }

google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerf" }