[versions]
activityCompose = "1.11.0"
agp = "8.13.0"
barcodeScanning = "17.3.0"
cameraCore = "1.5.0"
coilCompose = "2.7.0"
composeBom = "2025.09.00"
coreSplashscreen = "1.0.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
foundationAndroid = "1.9.1"
ktorClientAndroid = "3.3.0"
lifecycleViewmodelCompose = "2.9.4"
material = "1.13.0"
material3 = "1.5.0-alpha04"
materialIconsExtended = "1.7.8"
navigationCompose = "2.9.4"
navigationFragment = "2.9.4"
navigationUi = "2.9.4"
runtimeAndroid = "1.9.1"
kotlin = "2.2.20"
uiGraphicsAndroid = "1.9.1"
foundation = "1.9.1"
cameraView = "1.5.0"
foundationLayout = "1.9.1"

[libraries]
barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCore" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCore" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientAndroid" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientAndroid" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientAndroid" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorClientAndroid" }

material = { module = "com.google.android.material:material", version.ref = "material" }

material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "uiGraphicsAndroid" }
foundation-android = { group = "androidx.compose.foundation", name = "foundation-android", version.ref = "foundationAndroid" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }
ui = { module = "androidx.compose.ui:ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}